# Generated by Django 4.0.3 on 2022-03-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_profile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ration_number',
            field=models.CharField(default='Null', max_length=17, unique=True),
        ),
    ]
