# Generated by Django 4.0.3 on 2022-03-23 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_profile_ration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ration_number',
            field=models.CharField(default='Null', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Ration number must be entered in the format: '9999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
