# Generated by Django 4.0.3 on 2022-03-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_alter_profile_ration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ration_number',
        ),
    ]
