# Generated by Django 4.0.3 on 2022-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_remove_profile_ration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ration',
            field=models.CharField(default='Null', max_length=17),
        ),
    ]
